version: '3.1'
services:
  postgres:
    container_name: postgresql-docker-demo
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data:/data:ro

networks:
    default:
